language: cpp

dist: xenial

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tcsh
      - pkg-config
      - netcdf-bin libnetcdf-dev libnetcdff-dev
      - gfortran
      - gcc
      - wget
      #- lftp

install:
  # Fetch Icepack-specific dataset
  - "wget https://zenodo.org/record/3728287/files/Icepack_data-20200326.tar.gz &&
    tar xvfz Icepack_data-20200326.tar.gz -C ~"

  # Mirror entire data folder
  #- "lftp ftp://anonymous:travis@travis-ci.org@ftp.cgd.ucar.edu 
  #-e 'mirror /archive/Model-Data/CICE/ ~/ICEPACK_INPUTDATA; quit'"

script:
  # verify icepack.setup --case and icepack.setup --test don't error then run test suite
  - "./icepack.setup --case trcase --mach travisCI --env gnu --pes 1x1 -s diag1 && sleep 4"
  - "./icepack.setup --test smoke --testid trtest --mach travisCI --env gnu 
    --pes 1x1 -s diag1 && sleep 4"
  - "./icepack.setup --suite travis_suite --testid travisCItest 
    --mach travisCI --env gnu &&
    cd testsuite.travisCItest &&
    ./results.csh"

notifications:
  email: false

after_failure:
  - "for runlog in $TRAVIS_BUILD_DIR/testsuite.travisCItest/*.travisCItest/logs/icepack.runlog.*; do
    echo \"### Contents of $runlog ###\" && cat $runlog; done"
  - "git config --global user.email 'travis@travis-ci.org' &&
    git config --global user.name 'ciceconsortium' &&
    ./report_results.csh --travisCI"
